import sys
import FreeCAD
import Part
import Drawing
import TechDraw
import shutil
import importlib

# -----------------------------
# Reload modules ** for development only**
import ShapeFactory
importlib.reload(ShapeFactory)
# -----------------------------

from Draw import Draw
from Cuboid import Cuboid
from Cylinder import Cylinder
from HoleInBox import HoleInBox
from Wedge import Wedge
from SemiHoleInCuboid import SemiHoleInCuboid
from QuarterHoleInCuboid import QuarterHoleInCuboid
from SemiCircle import SemiCircle
from HoleInDoor import HoleInDoor
from QuarterCircle import QuarterCircle
from HoleInWedge import HoleInWedge
from ShapeFactory import ShapeFactory

# -----------------------------------
#   Document Object IDs and Types
# -----------------------------------
fusions = []
shapes = []
FUSION = 'Fusion'
SHAPE = 'Shape'

# Create id for the document object type and add it to the respective list
def generateID(objectType): 
	if objectType == FUSION:
		id = FUSION + str(len(fusions)+1 )
		fusions.append(id)
	return id

# -------------------------
#   Fusion
# -------------------------

def fusePart(doc, fuseID, baseID, toolID):
	doc.addObject("Part::Fuse", fuseID)
	doc.getObject(fuseID).Base = doc.getObject(baseID)
	doc.getObject(fuseID).Tool = doc.getObject(toolID)

def fuseCut(doc, fuseID, baseID, toolID):
	doc.addObject("Part::Cut", fuseID)
	doc.getObject(fuseID).Base = doc.getObject(baseID)
	doc.getObject(fuseID).Tool = doc.getObject(toolID)

def right(doc, base, new, unit, k):
	doc.getObject(new).Placement = FreeCAD.Placement(App.Vector(k*unit, 0, 0), App.Rotation(0,0,0))	
	id = generateID(FUSION) 
	fusePart(doc, id, base, new)
	return id

def behind(doc, base, new, unit, k):
	doc.getObject(new).Placement = FreeCAD.Placement(App.Vector(0, k*unit, 0), App.Rotation(0,0,0))	
	id = generateID(FUSION) 
	fusePart(doc, id, base, new)
	return id

def top(doc, base, new, unit, k):
	doc.getObject(new).Placement = FreeCAD.Placement(App.Vector(0, 0, k*unit), App.Rotation(0,0,0))	
	id = generateID(FUSION) 
	fusePart(doc, id, base, new)
	return id

# -------------------------
#  Algorithm
# -------------------------
matrixX = 3
matrixY = 3
matrixZ= 3
reachableNodes = {"0,0,0"}

class Node:
	def __init__(self, x, y, z):
		self.x = x
		self.y = y
		self.z = z
		self.reachable = False
		self.shape = None

def hash(x, y, z):
	return '{},{},{}'.format(x, y, z)

# Delete later?
def unhash(hashedString):
	stringCoords = hashedString.split(",")
	intCoords = []
	for i in range (0,3):
		intCoords[i] = int(stringCoords[i])
	return intCoords

def initMap(x, y, z):
	map = {}
	for i in range(0, x):
		for j in range (0, y):
			for k in range (0, z):
				map[hash(i, j, k)] = Node(i, j, k)
	return map

def checkReachability(nodeCoords):
	hashedString = hash(nodeCoords[0], nodeCoords[1], nodeCoords[2])
	adjacentNode = map[hashedString]
	if adjacentNode.shape is None and adjacentNode.reachable is False:
		adjacentNode.reachable = True
		reachableNodes.add(hashedString)

def relaxGraph(currentNode, reachableNodes):
	if currentNode.x != 0:
		checkReachability([currentNode.x - 1, currentNode.y, currentNode.z])
	if currentNode.x != matrixX - 1:
		checkReachability([currentNode.x + 1, currentNode.y, currentNode.z])
	if currentNode.y != 0:
		checkReachability([currentNode.x, currentNode.y - 1, currentNode.z])
	if currentNode.y != matrixY - 1:
		checkReachability([currentNode.x, currentNode.y + 1, currentNode.z])
	if currentNode.z != 0:		
		checkReachability([currentNode.x, currentNode.y, currentNode.z - 1])
	if currentNode.z != matrixZ - 1:
		checkReachability([currentNode.x, currentNode.y, currentNode.z + 1])	

def algorithm(doc, x, y, z, unit):
	shapeFactory = ShapeFactory(doc, unit)

	while len(reachableNodes) != 0:
		nodeHash = reachableNodes.pop()
		currentNode = map[nodeHash]
		currentNode.shape = shapeFactory.generateRandomShape()
		currentNode.reachable = False
		relaxGraph(currentNode, reachableNodes)
		 

# -------------   Main    -------------
doc = FreeCAD.newDocument()
map = initMap(matrixX, matrixY, matrixZ)
algorithm(doc, matrixX, matrixY, matrixZ, 100)
#Draw(doc, 'Templates/A1_Landscape_plain.svg', finalObjectID)
doc.recompute()
