from ShapeGenerator import ShapeGenerator
from Draw import Draw
from Exporter import Exporter

# -------------   Config    -------------
#EXPORT_PATH = 
MATRIX_X = 2
MATRIX_Y = 2
MATRIX_Z= 2
UNIT = 100

# -------------   Main    -------------
doc = FreeCAD.newDocument()
shapeGenerator = ShapeGenerator(doc, MATRIX_X, MATRIX_Y, MATRIX_Z, UNIT)
finalObjectID = shapeGenerator.generate('Easy')
Draw(doc, 'Templates/A1_Landscape_plain.svg', finalObjectID)
doc.recompute()

map = shapeGenerator.baseShapeMap
for k in map.keys():
	if map[k].shape != None and map[k].shape != "Empty" and map[k].shape.centrelineInfo != None:
		Draw.drawCentreline(doc, map[k], MATRIX_X, MATRIX_Y, MATRIX_Z, UNIT)

#exporter = Exporter(doc, EXPORT_PATH)
#exporter.saveDrawings(finalObjectID)
